name: EasyElevator
main: STtraveller.EasyElevator.EasyElevator
version: 8.3.1
api-version: 1.16
commands:
  elv:
    description: Elevator Commands
    usage: /elv
  eelevator:
    description: Elevator Commands
    usage: /eelevator